### PR TITLE
Mavenized project

### PR DESCRIPTION
**Pull request by stickfigure**
Corrected some issues with the last PR.

After you have a sonatype account and a gpg key set up, you can:

mvn release:prepare
mvn release:perform

### CODE REVIEW

**Comment by kellysutton** [comment]
Nice! We'll verify things and get this merged in.

**Comment by kellysutton** [comment]
Crap. Merged this too soon. Need to revert.

**Comment by kellysutton** [comment]
Alright, sorry about that. Can you reopen this PR as a branch once again? Running the unit tests was failing with the `ant junit` command.

**Comment by kellysutton** [comment]
Scratch all of that, I've pulled the mavenization into a new PR: https://github.com/imgix/imgix-java/pull/9

**Comment by stickfigure** [comment]
Cool. I almost have it all in a new PR but we're hitting the limits of my git-fu.

BTW you can run the tests with `mvn test`.

**Comment by kellysutton** [comment]
:+1: Sorry for all of the run-around. Just need to make some changes to the README to reflect the mavenization and then we'll be good to go.

**Pull request merged**
